### ISSUE TITLE
Привязка контекста

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/fsd4-slider#10]
https://github.com/fmvasilenko/fsd4-slider/blob/48c46ad1eb7baf02310806cff701c45652907616/src/demoSlider/DemoSlider.ts#L149-L160
Давай избавимся от ручной привязки контекста. Есть несколько вариантов, как этого добиться (использовать стрелочные функции в полях класса, bind-декораторы, плагины для babel и т.д.)

**Comment by fmvasilenko** [comment]
Я попробовал задавать хендлеры через стрелочные функции, но тут, к сожалению, возникла проблема:
Контекст выполнения невозможно перепривязать. Из-за этого не работают заглушки в тестах.
Я почитал разные статьи на эту тему и многие вообще не рекомендуют так делать ([пример](https://medium.com/@charpeni/arrow-functions-in-class-properties-might-not-be-as-great-as-we-think-3b3551c440b1))

Декораторы надо так же применять к каждому методу. Плагины, по сути, те же декораторы, только написанные не мной)

Ты можешь, пожалуйста, пояснить недостаток прямой привязки через `.bind(this)`?
Потому как мне кажется это очень простым и изящным решением.
Если вопрос только в меньшем количестве кода, то декоратор тоже надо писать, а потом применять к каждому методу (доп. код). Плагин дает примерно тот же эффект (например перед методами надо добавлять `@autobind`, что не сильно сокращает код.)

**Comment by Nelliza** [comment]
Насчет изящности поспорю - все же много лишнего кода получается, и обычно такая привязка делается в конструкторе (ты же можешь не единожды использовать эти методы, у тебя тоже кстати это встречается, что метод используется в нескольких местах и приходится дублировать эту привязку). В общем, не слишком удобный подход в плане расширяемости, с декораторами чище получается. Но настаивать не буду ) Учебный проект все-таки не настолько объемный, чтобы это было большой проблемой, так что выбор оставляю за тобой
