### ISSUE TITLE
Файловая структура

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/fsd4-slider#11]
![1](https://user-images.githubusercontent.com/19621113/99878511-fc603c00-2c16-11eb-9837-f9ded6fee397.png)
Выдели плиз и для презентера отдельную папку для единообразия с остальными слоями приложения

**Comment by Nelliza** [comment]
Стилевые файлы (_main.scss_, _slider.scss_) лучше также поместить в отдельную папку (_src_ -> _styles_)

**Comment by fmvasilenko** [comment]
> Стилевые файлы (_main.scss_, _slider.scss_) лучше также поместить в отдельную папку (_src_ -> _styles_)

Так а это же тогда не по БЭМ получается?
Может лучше из `main.scss` перенести все, что касается демо в папку `demoSlider`?
Тогда в `main` останутся только общие стили, а все, что касается отдельных частей - будет в отдельных папках.
И у меня изначально было две точки входа - для демо страницы и для сборки npm пакета и там было важно разделение стилевых файлов. Правда при изменении архитектуры потер вторую точку входа, сейчас от нее остался отдельный webpack конфиг.

**Comment by Nelliza** [comment]
> Так а это же тогда не по БЭМ получается?
> Может лучше из `main.scss` перенести все, что касается демо в папку `demoSlider`?
> Тогда в `main` останутся только общие стили, а все, что касается отдельных частей - будет в отдельных папках.

В целом ты прав, просто у тебя нет структурной разбивки по БЭМ, т.к. ты не выделял элементы слайдера в отдельные компоненты. Но выглядит логично, по поводу стилей демо - однозначно плюсую, их в _main.scss_ не должно быть

**Comment by Nelliza** [comment]
И кажется стили для `.slider-wrapper` тоже лишние, их тогда тоже выпили из _main.scss_

**Comment by Nelliza** [comment]
И в тестах тоже для презентера выдели плиз отдельную папку
