### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/fsd4-slider#12]
https://github.com/fmvasilenko/fsd4-slider/blob/78ae96c04a8a4c9b40ae8b97ea9bf35ae775fd68/src/slider/model/Model.ts#L68-L72
Этот код выглядит странным, тут по сути ты не устанавливаешь обновленные значения ползунков, а только проверяешь текущие значения (с их корректировкой при необходимости). Думаю, будет намного нагляднее, если ты добавишь классу `ModelMemoryCell` отдельный публичный метод для проверки текущего значения, и будешь вызывать именно его при изменении опций

**Comment by Nelliza** [comment]
https://github.com/fmvasilenko/fsd4-slider/blob/78ae96c04a8a4c9b40ae8b97ea9bf35ae775fd68/src/slider/model/Model.ts#L56-L59
Этот метод на мой взгляд избыточен - зачем осуществлять предварительную валидацию перед созданием инстанса класса `ModelMemoryCell`, если можно валидировать переданное значение в конструкторе класса?

Плюс мы таким образом избавимся от разнородности при создании полей класса модели:
https://github.com/fmvasilenko/fsd4-slider/blob/78ae96c04a8a4c9b40ae8b97ea9bf35ae775fd68/src/slider/model/Model.ts#L29-L37

**Comment by Nelliza** [comment]
https://github.com/fmvasilenko/fsd4-slider/blob/b8000b60dd4f62419ddfd93ebea2d5e40a9d21e9/src/slider/model/Model.ts#L64-L66
А подскажи плиз, для чего здесь дважды апдейтится `leftHandleValue`?

**Comment by fmvasilenko** [comment]
> https://github.com/fmvasilenko/fsd4-slider/blob/b8000b60dd4f62419ddfd93ebea2d5e40a9d21e9/src/slider/model/Model.ts#L64-L66
> 
> 
> А подскажи плиз, для чего здесь дважды апдейтится `leftHandleValue`?

Тут можно провести параллель с механическими ползунками на одной оси)
Модель строго задает допустимые состояния, в связи с чем один ползунок "упирается" в другой.
Таким образом если взять состояние
```js
{
  minValue: 0,
  leftHandleValue: 10,
  rightHandleValue: 20
}
```
А потом поменять `minValue` на `30`, то:
Двигаем левый ползунок до правого (20)
Двигаем правый ползунок до `minValue` (30)
Двигаем левый ползунок до `minValue` (30).

Логично спросить: а почему бы не двигать сначала правый ползунок, а потом левый?
Если оба ползунка окажутся больше `maxValue`, то ситуация ровно зеркальная и надо двигать сначала левый, а потом правый.

Остается 2 варианта:
1. Написать отдельную логику для определения того, какой ползунок двигать первым, с учетом всех возможных состояний
2. Сделать как сейчас

Мне показалось, что так проще, хотя, возможно, и не совсем очевидно) Может стоит добавить комментарий)

**Comment by Nelliza** [comment]
Да, я так и поняла, но это кажется не совсем очевидным ) Ага, давай коммент добавим
