### ISSUE TITLE
Деструктуризация

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/fsd4-slider#13]
https://github.com/fmvasilenko/fsd4-slider/blob/78ae96c04a8a4c9b40ae8b97ea9bf35ae775fd68/src/slider/model/ModelGUI.ts#L100-L108
Старайся использовать по возможности деструктурирующее присваивание - это облегчает как написание, так и чтение кода (посмотри плиз по всему проекту)

**Comment by Nelliza** [comment]
https://github.com/fmvasilenko/fsd4-slider/blob/b8000b60dd4f62419ddfd93ebea2d5e40a9d21e9/src/slider/view/HandleView.ts#L79-L97
Здесь тоже можно деструктурировать значения объекта `this.classes`, ну и еще по коду посмотри, где прям по нескольку раз встречаются вложенные поля

**Comment by fmvasilenko** [comment]
> Здесь тоже можно деструктурировать значения объекта `this.classes`, ну и еще по коду посмотри, где прям по нескольку раз встречаются вложенные поля

Я, если честно, сомневался на счет классов. Оставляя переменные с именами `leftHandle`, `rightHandle`, `rightHandleLabel`, не совсем очевидно для чего они нужны.
А если переименовывать их в `leftHandleClass`, `rightHandleClass`, то есть ли разница между `leftHandleClass` и `classes.leftHandle`?

**Comment by Nelliza** [comment]
Давай тогда оставим, согласна с тобой

**Comment by Nelliza** [comment]
https://github.com/fmvasilenko/fsd4-slider/blob/3fe2dbb215b617f8e0a08fbf4584502409e7502d/src/slider/model/Model.ts#L76-L86
Здесь я бы тоже деструктурировала `minValue` / `maxValue` аналогично методам внизу - и лаконичнее, и нагляднее
