### ISSUE TITLE
Неправильный шаг

### ISSUE THREAD

**Issue by kate-fsd** [fmvasilenko/fsd4-slider#26]
min 0, max 10, step 10
устанавливаем min например 8
1. step в панели и в данных слайдера не изменился, так и остался равным 10, хотя фактически он равен 2
2. перемещение бегунка происходит не в середине

**Comment by fmvasilenko** [comment]
https://github.com/fmvasilenko/fsd4-slider/commit/6c461086ac54ee9005d3bd6db9b7f70d95f854e8  
Эта задача связана с `min = max`. Я там поставил ограничения:
```ts
if (min > max - step) min = max - step;
if (max < min + step) max = min + step;
```
Соответственно, получается, что невозможно установить такие min и max, что `max - min < step` и описанная выше проблема уходит)  
Перемещение бегунка не в середине происходило из-за того, что в формуле расчета середины используется step, поэтому, технически, переход был "в середине", но не 2, а 10, что на шкале длиной 2 выглядело странно)
