### ISSUE TITLE
Имена

### ISSUE THREAD

**Issue by kate-fsd** [fmvasilenko/fsd4-slider#27]
leftHandleValue, rightHandleValue
Лучше изменить названия на начало/конец, потому что когда слайдер вертикальный это уже не лево/право

**Comment by kate-fsd** [comment]
Еще предложила бы отказаться от слов handle, value (maxValue..) в названиях параметров

**Comment by kate-fsd** [comment]
Еще в HandleView осталось лево/право
leftHandleLabelVertical)

**Comment by kate-fsd** [comment]
Переименовать ModelGUI

Где то имя subscibers, где то observers. Выбери какое нибудь одно

**Comment by fmvasilenko** [comment]
https://github.com/fmvasilenko/fsd4-slider/commit/e54233e0e6c5bf44b7d66f78f384f7e85cd7b014 - переименовал ModelGUI

**Comment by kate-fsd** [comment]
> переименовал ModelGUI

еще сам класс
![image](https://user-images.githubusercontent.com/66846004/108423107-80db4e80-7248-11eb-9094-3e12e577ecae.png)
