### ISSUE TITLE
Небольшие недочеты

### ISSUE THREAD

**Issue by kate-fsd** [fmvasilenko/fsd4-slider#28]
1. /* eslint-disable class-methods-use-this */
Если у тебя есть методы, не использующие this, но тесно связанные с классом их нужно сделать static

2. в Model убери наверху комментарии

3. Я тоже к тебе с bind) Лучше использовать декоратор, особенно бросается в глаза в этом месте
![image](https://user-images.githubusercontent.com/66846004/106397765-1640ab00-6420-11eb-832e-fac0261a46aa.png)

Ты пробовал подключать декоратор, тесты точно с ним не работают?

**Comment by kate-fsd** [comment]
Лучше создать константу classes перед объявлением класса. И в других файлах

![image](https://user-images.githubusercontent.com/66846004/107855512-c0163380-6e33-11eb-9d82-7317b9ed1b60.png)

**Comment by fmvasilenko** [comment]
https://github.com/fmvasilenko/fsd4-slider/commit/8b180619c784d5a365c6fe6d3919fc451d265add - Поменял импорт классов

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/108420032-4ff91a80-7244-11eb-933e-a3b42387ebef.png)

Лучше не вкладывать ifы, а выходить из функции. И блок после else лучше переносить на новую строку
