### ISSUE TITLE
Копипаст

### ISSUE THREAD

**Issue by kate-fsd** [fmvasilenko/fsd4-slider#29]
Много копипаста. Файлы ModelGUI, slider.ts .. Подобные однотипные методы можно объединить
![image](https://user-images.githubusercontent.com/66846004/106398723-b0572200-6425-11eb-883b-9a12622589fe.png)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/107855707-e9838f00-6e34-11eb-914a-a1d01a45d7ce.png)

Эти методы используются только для подписки
![image](https://user-images.githubusercontent.com/66846004/107855718-06b85d80-6e35-11eb-9717-a480266775b2.png)

this.modelGUI.subscribe('min', this.updateScaleValues(state));  читается нормально, я б еще updateScaleValues изменила на updateScale

**Comment by kate-fsd** [comment]
еще
![image](https://user-images.githubusercontent.com/66846004/107855797-9100c180-6e35-11eb-999b-4c62cf02d6d2.png)

**Comment by fmvasilenko** [comment]
> this.modelGUI.subscribe('min', this.updateScaleValues(state)); читается нормально, я б еще updateScaleValues изменила на updateScale

Здесь логика была такая: снаружи View не известно как он выглядит и какая у него архитектура. Соответственно, неоочевидно, что:
```ts
// Presenter
this.modelGUI.subscribe('min', this.view.updateScaleValues);
```  
Зато такой вариант выглядит вполне закономерным:
```ts
// Presenter
this.modelGUI.subscribe('min', this.view.updateMin);
```  
То есть здесь идет разделение логики: презентер только подписывает View на изменение отдельных параметров модели, но не знает что там конкретно происходит. А во view в этом методе может лежать пачка других методов-подписчиков, которые при дальнейшей разработке могут прибавляться/убавляться, не изменяя при этом Presenter и не выходя за пределы своего класса.  
  
Как вариант, можно снабдить View своими обзерверами, но, мне кажется, координально ничего не поменяется. Просто добавится дополнительная прослойка во View и мы будем подписывать обзерверы View на обзерверы Model.

**Comment by kate-fsd** [comment]
Если сильно хочется, можешь оставить. Но я б убирала такое. Задача учитывать расширение не стояла, а выглядит это не очень. Тем более что в читаемости не теряешь:
this.modelGUI.subscribe('min', this.updateScale(state));  -  при изменении min обновить шкалу - все логично
