### ISSUE TITLE
Подписка на обновления слайдера извне

### ISSUE THREAD

**Issue by kate-fsd** [fmvasilenko/fsd4-slider#30]
Сейчас панель конфигурации подписана только на изменения leftHandleValue и rightHandleValue. Она должна так же слушать все изменения в слайдере - min, max ... (тут вспомнилась ошибка с шагом из #26, она связана с этой проблемой, шаг не обновляется)

**Comment by fmvasilenko** [comment]
С учетом текущих изменений, теперь можно подписаться на любой параметр слайдера.  
В демо подписка идет только на значения ручек, т.к. остальные параметры меняются сначала в панели, а потом изменения отражаются в слайдере. Получается, что в данном случае слайдер подписан на изменения панели, а не наоборот.  
Ошибка с шагом была связана не с подпиской, а с моделью. В модели при обновлении max/min не обновлялся шаг. Сейчас проблема решена. В #26 я чуть подробнее описал
