### ISSUE TITLE
Организация подписки

### ISSUE THREAD

**Issue by kate-fsd** [fmvasilenko/fsd4-slider#31]
Сейчас подписка организованна довольно запутанно. Файл ModelGUI тяжело воспринимается. Не понятно зачем класс ModelGUI хранит в себе всех подписчиков, причем в единственном экземпляре. Я так понимаю извне на один слайдер можно подписаться только один раз? Это неправильно
Могу предложить тебе избавиться от лишних прослоек из однострочных методов. ModelMemoryCell возможно расширить классом Observable, а не хранить св-во observer (можно и оставить, на твое усмотрение). Для слайдера создать фасад(#32) с публичным методом sibscribe:

type ModelOption = 'leftHandleValue' | 'step' | 'minValue' ...
sibscribe(за_кем_следим: ModelOption, callback)

И такой же метод в модели

**Comment by fmvasilenko** [comment]
https://github.com/fmvasilenko/fsd4-slider/commit/af3662e58cf8734eb2dec6b6339b10a1747c36c7  
Поменял подписку на ModelGUI.  
ModelMemoryCell и Observable когда-то были единым объектом, но потом мы с Нелли это обсудили и решили разделить их на два. Не знаю, есть ли смысл сейчас все менять обратно) Пока оставил как есть)
