### ISSUE TITLE
Фасад

### ISSUE THREAD

**Issue by kate-fsd** [fmvasilenko/fsd4-slider#32]
Создать класс оболочку, которая будет хранить в себе MVC (экземпляры модели, вью, презентера) и предоставлять простые публичные методы для получения/установки данных, добавления подписчиков. 
Сейчас функцию фасада у тебя выполняет презентер. После переноса методов в презентере должна остаться только подписка модели на вью и вью на модель. Примерно то, что сейчас находится в методах setSubscriptions, leftHandleSubscriber, rightHandleSubscriber.

**Comment by fmvasilenko** [comment]
https://github.com/fmvasilenko/fsd4-slider/commit/b75975f2a526e588da63d46e641715e224bcb72b
