### ISSUE TITLE
Обработка ошибок

### ISSUE THREAD

**Issue by kate-fsd** [fmvasilenko/fsd4-slider#33]
1. Извне в слайдер могут прийти любые некорректные данные, например max как объект, так как пользователь, подключающий плагин может передать в него любую ерунду. Потому в этой строке:
export default $.fn.slider = function (this: JQuery, config?: Config)
config должен иметь тип не Config, а any. И уже в Модели ты должен обработать все нестандартные ситуации и привести конфиг к правильному типу
(про type guards - сужение типов https://www.typescriptlang.org/docs/handbook/advanced-types.html#typeof-type-guards)

2. Добавь вывод ошибок/предупреждений

3. Проверь, все ли логические ошибки обрабатываются: шаг не ноль, (макс - мин) не меньше шага и тд

**Comment by kate-fsd** [comment]
Сейчас выводятся ошибки несоответствия типа, но иногда такие данные можно молча привести к правильному ("5" к 5), можно и уведомить пользователя. А вот при логических нужно уведомить

**Comment by fmvasilenko** [comment]
> Сейчас выводятся ошибки несоответствия типа, но иногда такие данные можно молча привести к правильному ("5" к 5), можно и уведомить пользователя. А вот при логических нужно уведомить

#40
