### ISSUE TITLE
Подключение плагина

### ISSUE THREAD

**Issue by kate-fsd** [fmvasilenko/fsd4-slider#34]
Выведи конечные файлы слайдера в папку в корне проекта. В ней должны лежать два файла - css и js. В них не должно быть ничего связанного с панелью, не должно быть jquery, просто плагин, который ты можешь взять и подключить к себе на страницу.
Опиши в ридми как это сделать (это можно сделать позже, когда закончим со всеми правками)

**Comment by kate-fsd** [comment]
нету(
![image](https://user-images.githubusercontent.com/66846004/108421410-322cb500-7246-11eb-8191-41afda777d79.png)

**Comment by fmvasilenko** [comment]
А, так я добавил отдельный конфиг webpack. Файлы собирались в папку dist, а она в gitignore.  
Убрал из gitignore)
