### ISSUE TITLE
ModelMemoryCell

### ISSUE THREAD

**Issue by kate-fsd** [fmvasilenko/fsd4-slider#36]
Судя по названию и по коду этот класс используется для работы с одним параметром из модели. И в таком контексте метод getState выглядит неуместным.
 private getState: () => State; 
 interface State {
  isRange: boolean
  isVertical: boolean
...
}
Этому классу не обязательно знать что есть еще какие то параметры помимо текущего. Лучше уведомлять подписчиков, о том что изменилось значение именно этого параметра:
this.observer.publish({ [this.paramName]: this.value });

Либо в модели сделать подписку на все ModelMemoryCell и уже из модели отправлять подписчикам все параметры скопом (первый вариант мне нравится больше)

**Comment by fmvasilenko** [comment]
Первый вариант с публикацией только одного параметра:  
Для отрисовки компонентов, почти всегда, нужны несколько параметров из Model, а не один. И, поскольку, изменение одного параметра в Model могло вызвать изменение остальных, то нужно каждый раз запрашивать из Model текущее состояние.  Цепочка вызовов выглядит так:  
ModelMemoryCell публикует новое значение -> по цепочке подписчиков оно долетает до, например, Handle. -> Handle для отрисовки вызывает запрос общего состояния модели -> опять проходим по цепочке подписчиков до Model и собираем все в кучу -> возвращаем state для отрисовки.  
Мне показалось, что проще избавиться от второй части цепочки (дополнительные подписчики, логика и т.д.) и передавать сразу текущий стейт.  
Технически, разницы никакой, передавать один параметр или весь state, разве что не совсем "канонично") Но позволяет сэкономить на коде)  
То есть мы вызываем подписчика и сразу снабжаем его всей необходимой информацией, а не одним параметром. Лишних вызовов при этом нет
  
Второй вариант:  
Проблема в том, что придется либо создавать подписчика для каждого параметра отдельно, что опять добавляет кучу кода, либо подписчик будет один, но тогда при изменении любого параметра, например `scaleDisplayed`, будут вызваться абсолютно все внешние подписчики, даже не связанные с `scaleDisplayed` (будут пересчитывать положения бегунков и т.д.)  
  
Я тоже изначально думал над этими вариантами, но решил все таки остановиться на том, что есть сейчас, как на компромиссном)

**Comment by kate-fsd** [comment]
Мне кажется все проще)
В презентере подписка вью на модель сейчас выглядит так (на примере isRange)
`this.modelGUI.subscribe('isRange', this.view.updateIsRange);`

Тебе нужно передать все параметры модели. У модели есть публичный метод ModelGUI.getCurrentState
```
const state = this.modelGUI.getCurrentState()
this.modelGUI.subscribe('isRange', (isRange: boolean) => this.view.updateIsRange({ ...state, isRange }));
```

**Comment by kate-fsd** [comment]
И в MemoryCell соответственно не 
this.subscribers.publish(this.getState());
а this.subscribers.publish(this.value);
