### ISSUE TITLE
Обработка событий

### ISSUE THREAD

**Issue by kate-fsd** [fmvasilenko/fsd4-slider#37]
![image](https://user-images.githubusercontent.com/66846004/107856441-3a958200-6e39-11eb-9ebb-f2643bbf4d93.png)

1. Вся эта цепочка из проброшенных clicksubscriber плохо воспринимается

2. Плохое именование: 
- scaleClickExternalSubscriber  - не нужен External, не ожидаешь что эта еще и обработка клика подписей шкалы (проверь, нужна ли тебе вообще эта обработка в ScaleValueView, т.к. каждое деление и подпись являются частью шкалы, они должны обрабатываться при клике по ней ( в scaleNode.addEventListener('click', ... ). 
- clickHandler - handleScaleClick

3. private scaleClickExternalSubscriber: Function = () => {};
Тип Function ни о чем не говорит - что нужно передать подписчику, сколько аргументов

Чтобы облегчить восприятие подписки во вью, предлагаю:
1. объединить setLeftHandlePositionSubscriber, setRightHandlePositionSubscriber, setScaleClickSubscriber в один метод subscribe. По аналогии с моделью, например:
this.view.setLeftHandlePositionSubscriber(this.modelGUI.calculateFirstValue);   ->  this.view.subscribe('firstHandle', this.modelGUI.calculateFirstValue); 

2. сокращать слишком детализированные имена функции, например:
this.view.setLeftHandlePositionSubscriber(this.modelGUI.calculateFirstValue);  ->   this.view.subscribeFirstHandle
this.leftHandle.setPositionSubscriber(subscriber);   ->   this.leftHandle.subscribe

**Comment by fmvasilenko** [comment]
Клик по подписям обрабатывается отдельно, т.к. там другая логика. Когда происходит клик по шкале - берется положение мыши относительно шкалы и вычисляется значение. В случае с лейблами, можно нажать на край лейбла и , технически, положение мыши на лейбле 50 будет соответствовать, например, 49, вместо 50.
