### ISSUE TITLE
Архитектура

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/fsd4-slider#4]
_SliderConfig.ts_ - сюда, насколько я понимаю, ты поместил часть логики модели, следует перенести эту логику в модель, при этом сам конфиг лучше оставить. Т.е. по идее в этом файле должен остаться только конфиг, который будет импортироваться моделью. Т.к. конфиг - часть модели, этот файл и файл с самим классом модели лучше объединить в одну директорию (к примеру, папка _Model_ -> файлы _config.ts_ и _Model.ts_)

**Comment by Nelliza** [comment]
_SliderConfigItem.ts_ и _SliderStateItem.ts_ - много дублирующегося кода, из них нам по сути нужны 3 метода для реализации паттерна Observer (методы подписки, отписки и оповещения). Вот эти 3 метода следует вынести в отдельный класс (например, папка _Observable_ -> файл _Observable.ts_), от которого будут наследоваться другие классы при необходимости

**Comment by Nelliza** [comment]
Метод _checkPosition()_ тоже относится к модели, насколько я понимаю. При этом модель не должна знать ни о каких ползунках, позициях и т.д. Она мыслит категориями начальное / конечное значение, минимальное / максимальное и т.д. Т.е. тут еще надо подумать над грамотным именованием

**Comment by fmvasilenko** [comment]
> _SliderConfig.ts_ - сюда, насколько я понимаю, ты поместил часть логики модели, следует перенести эту логику в модель, при этом сам конфиг лучше оставить. Т.е. по идее в этом файле должен остаться только конфиг, который будет импортироваться моделью. Т.к. конфиг - часть модели, этот файл и файл с самим классом модели лучше объединить в одну директорию (к примеру, папка _Model_ -> файлы _config.ts_ и _Model.ts_)

Я попробовал реализовать ту схему, которую рисовал. Сейчас она в отдельной [ветке](https://github.com/fmvasilenko/fsd4-slider/tree/architecture-change)

Она еще не закончена, но архитектура вполне понятна.
Я соединил конфиг с моделью, а для вью сделал отдельный переходник-фасад

**Comment by Nelliza** [comment]
Таким образом, если разнести логически все нужное (описанные выше методы), а все лишнее убрать, должна получиться примерно следующая структура: папки _View_, _Model_, _Presenter_, _Observable_, внутри которых лежат файлы с соответствующими классами

**Comment by Nelliza** [comment]
Все, что относится к демо-странице, также лучше положить в отдельную директорию
