### ISSUE TITLE
Числовые параметры как строки

### ISSUE THREAD

**Issue by kate-fsd** [fmvasilenko/fsd4-slider#40]
```
$('#test').slider({
  min: '20',
})
```
Слайдер не создается, выводится предупреждение. Сделай так, чтобы 
1. слайдер создавался всегда, при любых параметрах
2. там где явно возможно преобразование, оно было

**Comment by fmvasilenko** [comment]
Я добавил парсинг значения из строки.  
А вот по поводу создания слайдера при любых параметрах у меня вопрос. Есть ли смысл это делать? Если передан неправильных конфиг - слайдер выкидывает ошибку. Это же вполне логично.  
Просто сейчас иначе придется дописать еще прилично логики, а в задании даже примерно не было ничего подобного описано) Может оставим как есть, это же тестовое задание?)

**Comment by kate-fsd** [comment]
Когда приходят совсем некорректные данные, которые нельзя привести к правильному типу (например min: 'someString'), заменяй их на дефолтные, а вместо ошибки просто выводи предупреждение, что данные не приняты (ну и хорошо если укажешь почему не приняты)

По поводу "слайдер создавать всегда", после решения ошибки #39, у тебя ж вроде все и так работает, при любых данных (если тип правильный)?

**Comment by fmvasilenko** [comment]
https://github.com/fmvasilenko/fsd4-slider/commit/9cdac2571a9b34ffc8236f5764089444ae0461ce  
Ишьюс были довольно близки, так что получился всего один коммит)  
Слайдер теперь создается всегда. Из строк парсятся числа, если это возможно. Если данные совсем некорректные - выводится предупреждение в консоль, с пояснениями.  
Проверки происходят на всех этапах (и при создании слайдера и при дальнейшем использовании). При создании слайдера, некорректные данные заменяются на дефолтные. Если слайдер уже был создан и пришли новые некорректные данные - они игнорируются.
