### ISSUE TITLE
Код

### ISSUE THREAD

**Issue by kate-fsd** [fmvasilenko/fsd4-slider#42]
![image](https://user-images.githubusercontent.com/66846004/108641126-aec1cc80-74ae-11eb-8452-efb2e8be02eb.png)

Это нужно упростить, читается с большим трудом

Будет лучше, если создавать параметры не с помощью этой функции
`this.min = Model.makeNumberMemoryCell(min, this.checkMin);`
а так 
`this.min = new ModelMemoryCell<number>(min, this.checkMin);`

Есть еще такая проблема:
![image](https://user-images.githubusercontent.com/66846004/108641273-78388180-74af-11eb-90ca-dcc28c2f2073.png)

config имеет тип any, а ты получаешь сразу правильный тип State. Предлагаю 
1. либо в Model сначала привести к правильному типу, а потом создавать ModelMemoryCell
2. либо в ModelMemoryCell передавать параметр с типом any, и уже там преобразовывать к правильному

**Comment by fmvasilenko** [comment]
> Будет лучше, если создавать параметры не с помощью этой функции
> `this.min = Model.makeNumberMemoryCell(min, this.checkMin);`
> а так
> `this.min = new ModelMemoryCell<number>(min, this.checkMin);`
  
Изначально так и было, но в тот момент, когда я добавил проверку типов - пришлось усложнить логику. Предположим, плагин используется под чистый JS, а не TS. Дженерики работать не будут. Проверку типов надо осуществлять вручную. Для каждого ModelMemoryCell надо передавать тип в виде строки.  
Чтобы не передавать его в конструкторе, я делаю декоратор для проверяющей функции.  
Было бы изящно, если бы можно было вынимать тип из дженерика и автоматически передавать его в виде строки в проверяющую функцию, но, насколько я знаю, это невозможно. Отсюда и нагромождения логики) Попробую немного упростить, но пока не вижу как можно совсем от этого избавиться)

**Comment by fmvasilenko** [comment]
> config имеет тип any, а ты получаешь сразу правильный тип State. Предлагаю
> 
> 1. либо в Model сначала привести к правильному типу, а потом создавать ModelMemoryCell
> 2. либо в ModelMemoryCell передавать параметр с типом any, и уже там преобразовывать к правильному

`config` и правда имеет тип `any`, но `defaultConfig` имеет тип `State`. Соответственно в данном случае мы берем дефолтный конфиг, со всеми необходимыми нам полями. Расширяем его с помощью `config`. Если имена полей совпадают - данные изменяются.  
То есть таким образом происходит фильтрация полей объекта. На выходе мы получаем объект, у которого есть все необходимые поля + еще какие-то. Через деструктуризацию мы вынимаем из него то, что нам надо, а остальное просто игнорируется. Получается довольно изящный способ фильтрации, без нагромождений `if..else`  и прочего)  
TS к такому тоже относится благосклонно, т.к. все необходимые поля гарантированно существуют.  
  
Дальше остается только проверить соответствие типов и значений допустимым. Но это уже реализуется в каждом ModeMemoryCell

**Comment by kate-fsd** [comment]
Если в config приходит { min: boolean }, min из defaultConfig будет перезаписан на неправильный тип. Так что просто написать что это тип State - не пойдет.

Эти три функции (первый скрин) мне не нравятся тем, что они по сути делают простую операцию - проверку типа, а написаны сложно. Функция checkFunction два раза пробрасывается, захламляя этим код. То, чем занимается функция typeCheckDecorator не соответствует ее названию - не угадаешь что она возвращает checkFunction. И имя - не по стандарту. Кстати в подобных функциях лучше сначала создать хорошо именованную константу, потом ее возвращать.

Резюмируя все это - нужно сделать то, что написано в первом сообщении

**Comment by kate-fsd** [comment]
Я б предложила тебе немного отрефакторить так:

0. Заменить any на unknown)

1. Создаем тип, который делает все поля в State необязательными и unknown (ознакомиться с mapped types можно тут https://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types)
![image](https://user-images.githubusercontent.com/66846004/109160803-537e2b80-7787-11eb-817b-939f7de8e6ec.png)

2. Возвращаем config, убираем полностью функцию setInitialState. Теперь при создании ModelMemoryCell передается сразу значение из config (если оно было)
![image](https://user-images.githubusercontent.com/66846004/109160867-685abf00-7787-11eb-9da0-0dbbb5c1bb45.png)

3. в checkIfNumber, checkIfBoolean, checkMin и подобных у value тип unknown:
```
private static checkIfNumber(value: unknown): number
```

4. В ModelMemoryCell 
![image](https://user-images.githubusercontent.com/66846004/109160992-96400380-7787-11eb-9832-16bed48bd4a3.png)

![image](https://user-images.githubusercontent.com/66846004/109161027-a22bc580-7787-11eb-9bec-1e67576c20a6.png)

![image](https://user-images.githubusercontent.com/66846004/109161055-ac4dc400-7787-11eb-87bf-410fbfbd879b.png)

**Comment by kate-fsd** [comment]
Это рекомендация, так все хорошо. Пока ишью не закрываю

**Comment by fmvasilenko** [comment]
Я столкнулся с одной проблемой:  
`ModelMemoryCell` устроена таким образом, что если в нее передано неправильное значение - она его игнорирует и сохраняет свое предыдущее состояние. А вот если это первичная инициализация - то предыдущего состояния как такового нет и, чтобы оно было - надо в конструктор передавать еще и defaultValue.  
```ts
this.isRange = new ModelMemoryCell(isRange, defaultConfig.isRange, this.checkIfBoolean);
this.isVertical = new ModelMemoryCell(isVertical , defaultConfig.isVertical , this.checkIfBoolean);
this.valueLabelDisplayed = new ModelMemoryCell(valueLabelDisplayed, defaultConfig.valueLabelDisplayed, this.checkIfBoolean);
...
```
В текущей реализации сначала происходит инициализация с дефолтным конфигом, а потом уже через `set` записываются значения. Таким образом, первичная проверка ничем не отличается от последующих.  
Как лучше эту проблему решить? Передавать в конструктор еще и defaultValue, для правильной инициализации, или оставить `setInitialState`?

**Comment by kate-fsd** [comment]
Как тебе больше нравится) Мне наверное больше нравится передавать дефолтное. Если оставляешь первоначальный вариант то можешь просто поправить типы в некоторых местах
