### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/fsd4-slider#6]
![1](https://user-images.githubusercontent.com/19621113/98841624-70515600-2459-11eb-8cf2-43af88d38b67.gif)
При отключении интервала у слайдера наличие активного поля со значением второго ползунка сбивает с толку. Лучше или не отображать его в этом случае, или хотя бы дизейблить (менее предпочтительный вариант, имхо)

**Comment by Nelliza** [comment]
Именование полей со значениями ползунков в стиле "левый / правый" тоже предлагаю поправить - при смене ориентации слайдера эти характеристики становятся некорректными

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/98842318-6bd96d00-245a-11eb-9073-587ba5f67ef6.png)
Также мне кажется не совсем логичным неравномерное распределение меток, тут я тоже вижу 2 варианта:

- вообще не предоставлять возможность выбора количества таких меток и просто отображать максимально возможное количество (как сейчас в случае превышения максимального предела);
- корректировать введенное значение до ближайшего возможного, обеспечивающего равномерное распределение меток.

PS. Первый вариант мне кажется более очевидным )

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/98843461-12723d80-245c-11eb-9841-23afbcca7568.png)

Также мне кажется не совсем логичным неравномерное распределение меток, тут я тоже вижу 2 варианта:

- вообще не предоставлять возможность выбора количества таких меток и просто отображать максимально возможное количество (как сейчас в случае превышения максимального предела);
- корректировать введенное значение до ближайшего возможного, обеспечивающего равномерное распределение меток.

PS. Первый вариант мне кажется более очевидным )

**Comment by fmvasilenko** [comment]
> ![1](https://user-images.githubusercontent.com/19621113/98842318-6bd96d00-245a-11eb-9073-587ba5f67ef6.png)
> Также мне кажется не совсем логичным неравномерное распределение меток, тут я тоже вижу 2 варианта:
> 
> * вообще не предоставлять возможность выбора количества таких меток и просто отображать максимально возможное количество (как сейчас в случае превышения максимального предела);
> * корректировать введенное значение до ближайшего возможного, обеспечивающего равномерное распределение меток.
> 
> PS. Первый вариант мне кажется более очевидным )

Здесь встает тогда проблема выбора оптимального количества. И я не вижу очевидного решения.(
А в данном случае проблема на пользователе (разработчике) и он выбирает такие значения, чтобы было симметрично, не было перекрытия меток, но при этом чтобы было достаточное количество.

**Comment by fmvasilenko** [comment]
> Здесь тогда встает проблема выбора оптимального количества. И я не вижу очевидного решения.(
> А в данном случае проблема на пользователе (разработчике) и он выбирает такие значения, чтобы выглядело симметрично, не было перекрытия меток, но при этом количество было достаточным.

Если этот процесс автоматизировать, то я вижу 3 решения:
1. Делать максимально возможное количество меток (равное количеству шагов, по сути), тогда в большинстве случаев будет перекрытие.
2. Делать всегда одно и то же количество. Дешево и сердито)
3. Высчитывать ширину шкалы, ширину каждого лейбла, расчитывать оптимальное количество исходя из этих параметров.

Либо оставить так, как есть. Получаем гибкость настройки, но не сильно красивый внешний вид, если настройки не удачные (математически при этом все корректно)

**Comment by fmvasilenko** [comment]
А, еще можно искать ближайшее число к `pointsNumber`, на которое `maxValue-minValue` делится без остатка и брать его.
Но есть 2 но:
1. Не очевидное для пользователя поведение модуля.
2. Если диапазон равен простому числу, а шаг не равен 1, то решения нет в принципе.

**Comment by Nelliza** [comment]
> 2. Делать всегда одно и то же количество. Дешево и сердито)

Здесь я бы выбрала второй вариант, как раз по этой причине )

**Comment by Nelliza** [comment]
> > Здесь тогда встает проблема выбора оптимального количества. И я не вижу очевидного решения.(
> > А в данном случае проблема на пользователе (разработчике) и он выбирает такие значения, чтобы выглядело симметрично, не было перекрытия меток, но при этом количество было достаточным.
> 
> Если этот процесс автоматизировать, то я вижу 3 решения:
> 
> 1. Делать максимально возможное количество меток (равное количеству шагов, по сути), тогда в большинстве случаев будет перекрытие.
> 2. Делать всегда одно и то же количество. Дешево и сердито)
> 3. Высчитывать ширину шкалы, ширину каждого лейбла, расчитывать оптимальное количество исходя из этих параметров. Это довольно сложный способ.
> 
> Либо оставить так, как есть. Получаем гибкость настройки, но не сильно красивый внешний вид, если настройки не удачные (математически при этом все корректно)

Тут наверное что-то между первым и вторым вариантами - отталкиваться от количества шагов, при этом определить max количество меток, вмещающихся без перекрытия, и в случае, если количество шагов будет превышать эту величину - сокращать вдвое.

К примеру, max количество меток без перекрытия = 20, а количество шагов = 36
36 > 20, следовательно, сокращаем вдвое: 36 / 2 = 18
18 <= 20, что соответствует условию, значит оставляем 18 делений

**Comment by Nelliza** [comment]
И это кстати тоже дешево и сердито )

**Comment by fmvasilenko** [comment]
Я поправил логику, но просто на всякий случай опишу почему не использовал этот вариант ранее:
Если число шагов равно не 36, а, например, 60, то, используя эту формулу, получится 15 меток на шкале, хотя 60 прекрасно делится на 20, и можно было уместить все 20 меток.

**Comment by Nelliza** [comment]
Да, тут приходится жертвовать точностью расчетов в пользу простоты решения )

**Comment by Nelliza** [comment]
Добавь плиз курсор `pointer` для ползунка и тултипа )
