### ISSUE TITLE
Баги слайдера

### ISSUE THREAD

**Issue by Nelliza** [fmvasilenko/fsd4-slider#7]
![1](https://user-images.githubusercontent.com/19621113/98845273-86154a00-245e-11eb-9d3e-93d655bc8e86.gif)
При одинаковых значениях обоих ползунков клик на шкалу справа от ползунков не срабатывает

**Comment by fmvasilenko** [comment]
> ![1](https://user-images.githubusercontent.com/19621113/98845273-86154a00-245e-11eb-9d3e-93d655bc8e86.gif)
> При одинаковых значениях обоих ползунков клик на шкалу справа от ползунков не срабатывает

Верно. По задумке, эта возможность должна совсем пропадать,если включен диапазон, т.к. не понятно какой ползунок должен реагировать на нажатия.
Поправлю.

**Comment by Nelliza** [comment]
> > При одинаковых значениях обоих ползунков клик на шкалу справа от ползунков не срабатывает
> 
> Верно. По задумке, эта возможность должна совсем пропадать,если включен диапазон, т.к. не понятно какой ползунок должен реагировать на нажатия.
> Поправлю.

Тут все-таки не совсем корректно, я считаю - выглядит так, как будто что-то сломалось. Здесь либо вообще исключить возможность задания одинаковых значений ползунков (т.к. это в принципе нелогично для интервального слайдера), либо перемещать соответствующий ползунок (т.е. правый при клике справа от текущего значения, левый соответственно при клике влево). Первый вариант предпочтительнее, но я не настаиваю на нем )

**Comment by fmvasilenko** [comment]
> Тут все-таки не совсем корректно, я считаю - выглядит так, как будто что-то сломалось. Здесь либо вообще исключить возможность задания одинаковых значений ползунков (т.к. это в принципе нелогично для интервального слайдера), либо перемещать соответствующий ползунок (т.е. правый при клике справа от текущего значения, левый соответственно при клике влево). Первый вариант предпочтительнее, но я не настаиваю на нем )

Я бы тогда разделил этот вопрос на 2:
1. Могут ли ползунки принимать одинаковые значения? Мне кажется, это не принципиально. Главное, чтобы не перескакивали друг за друга. Я во многих слайдерах видел, что можно задать одинаковое значение, но ползунки часто накладываются один на другой. Чтобы этого избежать, у меня добавлена анимация со смещением ползунков, когда они рядом.
2. До исправлений по этому ишью, левый ползунок перемещался при нажатии на шкалу. Если включен диапазон, то он просто упирался в правый ползунок, чтобы не возникало недопустимых ситуаций. То есть это даже не баг, а вполне логичное поведение, с учетом того, что описано в модели.

> либо перемещать соответствующий ползунок (т.е. правый при клике справа от текущего значения, левый соответственно при клике влево)

Так можно сделать, но что, если клик произошел между ползунками? Можно
1. Не реагировать
2. Двигать ближайший к событию ползунок

P.S. Это очень похоже на ситуацию с календарем)

**Comment by Nelliza** [comment]
> 1. Могут ли ползунки принимать одинаковые значения? Мне кажется, это не принципиально. Главное, чтобы не перескакивали друг за друга. Я во многих слайдерах видел, что можно задать одинаковое значение, но ползунки часто накладываются один на другой. Чтобы этого избежать, у меня добавлена анимация со смещением ползунков, когда они рядом.

Думаю, такой вариант вполне допустим, так что соглашусь, что не принципиально )

**Comment by Nelliza** [comment]
> Так можно сделать, но что, если клик произошел между ползунками? Можно
> 
> 1. Не реагировать
> 2. Двигать ближайший к событию ползунок

Здесь однозначно второй вариант, потому что отсутствие реакции на клик по шкале выглядит так, как будто что-то сломалось )
